### ISSUE TITLE
Telit Module does not answer commands

### ISSUE THREAD

**Issue by alvarolb** [ameltech/sme-le51-868-library#10]
I think I have a problem with the Telit module. The device stopped to answer any command. It does not enter in configuration mode, it does not send any message... Is there any other way to test if the module is alive?

**Comment by alvarolb** [comment]
After digging into the library, I was able to talk with the module by just initializing the antenna with:

```cpp
sfxAntenna.begin(19200, &SigFox);
```

It is strange, as the library should be doing that by default, as described here:

```cpp
#ifdef ASME3_REVISION
    void begin (unsigned long baudRate=19200, Uart *_antenna=&iotAntenna);
#elif ARDUINO_SAMD_SMARTEVERYTHING_FOX
    void begin (unsigned long baudRate=19200, Uart *_antenna=&SigFox); 
#else
    void begin (unsigned long baudRate=19200, Uart *_antenna=&Serial1);
#endif
```

Maybe the `ARDUINO_SAMD_SMARTEVERYTHING_FOX` is not properly set?

**Comment by searobin** [comment]
Thanks a lot Alvaro.

This is very strange indeed. Anyway you should have the ASME3_REVISION.
I suppose you are using the Arrow board library not the Amel-tech one

**Comment by alvarolb** [comment]
I was using the AMEL-Tech Boards. With the Arrow Boards one seems to be working fine without modifying the code. Whis is the one I should use?

**Comment by searobin** [comment]
Good.
Thanks a lot.
Amel-tech is obsoleted, It is actually mentioned in the Board library description.
