### ISSUE TITLE
SmartEverything Fox in Star Network Protocol mode

### ISSUE THREAD

**Issue by MansourM61** [ameltech/sme-le51-868-library#11]
Hi Everyone,

From Telit LE51-868-S datasheet, it is possible to use the module in Star Network Protocol mode as well. In this mode, it is possible to establish a point to point radio link between two Telit modules.
1- Now I wonder if the library shipped with SmartEverything provides this feature.
2- I went through the .h header file and I noticed there is not a specific function for receiving data from SigFox module. Am I mistaken or actually the receiving function is missing?

Cheers.

**Comment by smkkHw** [comment]
Good evening here the answer fro both your points
1- No The library does not cover that functionalities, it is designed to work with SigFox network only. Even if, as You correct point to, the Telit chip mounted on ASME  is able to cover the Star Network Protocol
2- The SfxDownlink example show the downstream possibility with the SigFox network

Mik

**Comment by MansourM61** [comment]
Thanks for your help.
I managed to do it. It is pretty simple. Apart from SigFox network, the Telit modules can also operate in transparent mode and addressed secured mode. These modes are very useful when you need the modules to work in an area with no SigFox network. Or you only need a point-to-point RF link. Or maybe you need a small indoor network. I tried them both on my two modules, they're working fine.
I'd love to share the codes with you guys if you like to add this feature to your developing library.
Cheers.

**Comment by smkkHw** [comment]
This is an openSW, so feel free to add your part for the StarNetwork.

just remember 2 point

1) Some example to help other guy to play with.
2) Sign It !!!! Your name is appreciated.

Mik
