### ISSUE TITLE
SigFox Fw Upgrade

### ISSUE THREAD

**Issue by El-Fitz** [ameltech/sme-le51-868-library#5]
Hi !

So, tried updating firmware using the FwUpgrade example (didn't touch a single line, I swear !), chose sw upgrade, noticed my firmware version really wasn't up to date, proceeded with the upgrade, and... the sw upgrade failed.

So I had a totally unresponsive Telit module. Not a big deal, I unplugged the board, closed the JP1 jumper as said in the comments (doing so it lights up the D4 LED, correct ?), powered the board back on, and went with the HW upgrade. Everything went well, powered off, opened back the JP1 jumper, powered back on... and my Telit module stil isn't responding.

sfxAntenna.hasSfxAnswer() will only answer 0, and the whole module is basically useless now.

Did I miss something ?

**Comment by smkkHw** [comment]
Ciao.

It could be that the baudrate is the one used for the FW-Download (115200), which is not the default one used by the example (19200)
from SmeSFX.h:
    void begin (unsigned long baudRate=19200);

No Problem U have 2 possibility
1) change all the sfxAntenna.begin() in sfxAntenna.begin(115200)
2) run again ChangeSerialBaudrate.ino configuring back the 19200  baudrate

**Comment by El-Fitz** [comment]
Hi !

I tried res... Oh.
You know what I forgot when editing ChangeSerialBaudRate to reset it ?

To replace `sfxAntenna.begin()` with `sfxAntenna.begin(19200)`
Solved now !

Thanks a lot !

**Comment by smkkHw** [comment]
No problem.

an Happy SmartEverything user is our mission :) :)
