### ISSUE TITLE
Failing to get an answer from SigFox backend

### ISSUE THREAD

**Issue by R-Francois** [ameltech/sme-le51-868-library#7]
Hi,

I am currently trying to get an answer from SigFox Backend with the smarteverything board.
I have already created a ticket for my issue on http://www.arrowsmarteverything.com/ and Mik has begun to help me. Maybe, people are in the same situation than me, so I post a message here too.

I am using Arduino Software.
I transferred into the board the example code “ SfxDownlink.ino” from the library.
This program must send and receive data from SigFox when button1 is pressed.
On SigFox backend, I set Downlink mode to “Direct” and Downlink data to “{time}{rssi}0000”.

When I press the button in order to send the data, sfxAntenna.getSfxError() does not return SME_SFX_OK but SME_SFX_KO. If I print sfxAntenna.getLastReceivedMessage(), I get: "ERROR¥¥¥¥¥¥¥¥¥¥¥¥¥"
This message is displayed as soon as I pressed the button.

Moroever, there is no green down arrow into the SigFox Backend. 
In fact with the function sfxAntenna.sfxSendData(), message is displayed with a
gray up arrow. But when I use sfxAntenna.sfxSendDataAck(), nothing appears on the Backend. It seems that the message is not sent...

I could not find any information about this.
Thank you in advance for helping me with this issue.

**Comment by NaKroTeK** [comment]
Hi, 
Small Questions, Does Sigfox cover your location ? Is your location interfering  the signal ? Can you try outside or elsewhere ?

**Comment by smkkHw** [comment]
This issue on  http://www.arrowsmarteverything.com/ is resolved.
The point was the wrong FW Version plus the fact that it was not in a good position for the antenna.

in attach the thread.

Mik
[Ticket-943019.pdf](https://github.com/ameltech/sme-le51-868-library/files/385951/Ticket-943019.pdf)
